[build]
  publish = "public"
  command = "hugo"

[context.build]
  HUGO_VERSION = "0.50"

[context.production.environment]
  HUGO_VERSION = "0.50"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

  [context.deploy-preview.environment]
  HUGO_VERSION = "0.50"

  [context.branch-deploy.environment]
  HUGO_VERSION = "0.50"
